### PR TITLE
Added Open API article file and images

### PR DESCRIPTION
**Pull request by Kvaibhav01**
Please consider my first article for Firecmap. The details are shared with @shreya-gr.

### CODE REVIEW

**Comment by Nishchit14** [comment]
Thank you @Kvaibhav01 for creating your first blog PR. This is being crashed due to the hero section in frontmatter. You can find an image from Unsplash temporarily to get this PR deploy.

Here you can see the log, https://app.netlify.com/sites/firecamp-blog/deploys/5ea86c6700ce3a0006df162c

image

**Comment by Kvaibhav01** [comment]
@Nishchit14 I've added an image as you said.

**Comment by Nishchit14** [comment]
@Kvaibhav01 I am facing this error while testing it in local, have you checked it?
image

**Comment by Kvaibhav01** [comment]
I don't know about the error. I'm here to submit the article.

**Comment by Nishchit14** [comment]
@Kvaibhav01 somewhere your formating is causing this error. I am hoping that while writing the blog you check it's a preview in your local first.

**Comment by Kvaibhav01** [comment]
Check out the updated changes.

**Comment by Nishchit14** [comment]
@Kvaibhav01 Thanks for writing it. 

@shreya_gr This is an incomplete post for the following reason
1. Unsplash image credit yet to be given
2. Screenshots are not as per Firecamp standards ([Here](https://doc.firecamp.io/apis/impressions/request-body/) is the reference for screenshot styles)
3. Markdown formatting needs to be done properly. 
4. Author entry is not added in author list and due to it the app is crashing all the time
5. The author is using third party markdown tools to write content instead of installing this repo in local and see the Gatsby preview. (which is quite needed in our case)

I'll take care of all these changes from my end. Thanks.

**Pull request merged**
